# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build

on:
  push:
    branches:
      - 'dev'
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: yarn

#      - name: Linter Checks
#        run: yarn lint

      - name: Build Application
        run: yarn build:dirty

      - name: Unit Tests
        run: yarn test:ci

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .conf/Dockerfile
          push: true
          # build tag :dev with commit-sha and latest
          tags: ${{ steps.meta.outputs.tags }}_${{ env.COMMIT_SHA }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

  auth-and-dispatch:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ORG_PORTAL_DISPATCH_APPID }}
          application_private_key: ${{ secrets.ORG_PORTAL_DISPATCH_KEY }}

      # The triggered workflow isn't enabled for branch names / github.ref_name containing special characters like '/' for example 'feature/...'
      - name: Trigger workflow
        id: call_action
        env:
          TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          curl -v \
            --request POST \
            --url https://api.github.com/repos/catenax-ng/product-portal-cd/actions/workflows/portal-registration-image-update.yml/dispatches \
            --header "authorization: Bearer $TOKEN" \
            --header "Accept: application/vnd.github.v3+json" \
            --data '{"ref":"main", "inputs": { "new-image":"${{ github.ref_name }}_${{ env.COMMIT_SHA }}" }}' \
            --fail
